# Generated by Django 4.0 on 2023-07-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monformulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Monformulaire',
                'verbose_name_plural': 'Monformulaire',
            },
        ),
    ]
