# Generated by Django 4.0 on 2023-07-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('detail', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Monformulaire',
                'verbose_name_plural': 'Monformulaire',
            },
        ),
        migrations.DeleteModel(
            name='Monformulaire',
        ),
    ]
