# Generated by Django 4.0 on 2023-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_client_contact_delete_monformulaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='mon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
