# Generated by Django 4.0 on 2023-07-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_mon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mon',
        ),
    ]
