# Generated by Django 4.0 on 2023-07-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_delete_mon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_contact',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='client_contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client_contact',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client_contact',
            name='telephone',
        ),
    ]
