# Generated by Django 4.0 on 2023-07-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0008_delete_client_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('telephone', models.FloatField(max_length=50)),
                ('detail', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Client_contact',
                'verbose_name_plural': 'client_contact',
            },
        ),
    ]
