# Generated by Django 4.0 on 2023-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contact',
            name='detail',
            field=models.TextField(max_length=500),
        ),
    ]
