# Generated by Django 4.0 on 2023-07-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_alter_client_contact_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_contact',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
