# Generated by Django 4.0 on 2023-07-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscription_formulaire',
            new_name='InscriptionFormulaire',
        ),
    ]
