# Generated by Django 4.0 on 2023-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_inscription_formulaire_inscriptionformulaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscriptionformulaire',
            options={'verbose_name': 'InscriptionFormulaire', 'verbose_name_plural': 'InscriptionFormulaire'},
        ),
        migrations.AlterField(
            model_name='inscriptionformulaire',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
    ]
