# Generated by Django 4.0 on 2023-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_inscriptionformulaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionformulaire',
            name='date_de_naissance',
            field=models.DateField(),
        ),
    ]
