# Generated by Django 4.0 on 2023-07-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_inscriptionformulaire_date_de_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionformulaire',
            name='date_de_naissance',
        ),
    ]
