# Generated by Django 4.0 on 2023-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_inscriptionformulaire_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionformulaire',
            name='nom',
            field=models.CharField(default='Anonymes', max_length=150),
        ),
    ]
