# Generated by Django 4.0 on 2023-07-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_inscriptionformulaire_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionformulaire',
            name='choix',
            field=models.BooleanField(default=False),
        ),
    ]
