# Generated by Django 4.0 on 2023-07-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_inscriptionformulaire_choix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionformulaire',
            name='choix',
        ),
    ]
