# Generated by Django 4.0 on 2023-07-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_inscriptionformulaire_choix'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionformulaire',
            name='choix',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
