# Generated by Django 4.0 on 2023-07-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_inscriptionformulaire_choix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWordpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_c', models.CharField(max_length=150)),
                ('Nom_e', models.CharField(max_length=150)),
                ('telephone', models.PositiveIntegerField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('addresses', models.CharField(max_length=50)),
                ('decryption', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'ClientWordpress',
                'verbose_name_plural': 'ClientWordpress',
            },
        ),
    ]
