# Generated by Django 4.0 on 2023-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_rename_clientecommerce_client_ecommerce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionformulaire',
            name='choix',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client_ecommerce',
            name='telephone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='clientvitrine',
            name='telephone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='clientwordpress',
            name='telephone',
            field=models.PositiveIntegerField(),
        ),
    ]
