# Generated by Django 4.0 on 2023-07-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_inscriptionformulaire_choix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptionformulaire',
            name='choix',
        ),
    ]
