# Generated by Django 4.0 on 2023-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_inscriptionformulaire_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50, null=True)),
                ('Nom_client', models.CharField(max_length=150)),
                ('Nom_entreprise', models.CharField(max_length=150)),
                ('telephone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('addresses', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50, null=True)),
                ('decryption', models.CharField(max_length=1000)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('hebergement', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ClientEcommerce',
                'verbose_name_plural': 'ClientEcommerce',
            },
        ),
        migrations.RenameModel(
            old_name='InscriptionFormulaire',
            new_name='ClientFormation',
        ),
        migrations.DeleteModel(
            name='Client_eCommerce',
        ),
        migrations.AlterModelOptions(
            name='clientformation',
            options={'verbose_name': 'ClientFormation', 'verbose_name_plural': 'ClientFormation'},
        ),
        migrations.AddField(
            model_name='clientvitrine',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientvitrine',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientvitrine',
            name='hebergement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientvitrine',
            name='statut',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientvitrine',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientvitrine',
            name='zone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientwordpress',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientwordpress',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientwordpress',
            name='hebergement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientwordpress',
            name='statut',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientwordpress',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientwordpress',
            name='zone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
