# Generated by Django 4.0 on 2023-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_clientecommerce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecommerce',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clientvitrine',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clientwordpress',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
