# Generated by Django 4.0 on 2023-07-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_alter_clientecommerce_telephone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientecommerce',
            old_name='type',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='clientvitrine',
            old_name='type',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='clientwordpress',
            old_name='type',
            new_name='types',
        ),
    ]
