# Generated by Django 4.0 on 2023-07-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_rename_type_clientecommerce_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecommerce',
            name='decryption',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientvitrine',
            name='decryption',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientwordpress',
            name='decryption',
            field=models.TextField(max_length=1000),
        ),
    ]
